name: AIS Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run AIS monitor
        env:
          AIS_EMAIL_PASSWORD: ${{ secrets.AIS_EMAIL_PASSWORD }}
        run: python ais_monitor.py --once
      
      - name: Commit and push results
        run: |
          git config user.name 'AIS Monitor Bot'
          git config user.email 'actions@github.com'
          git add -A out/
          git add ais_monitor.log ais_trails.db || true
          if ! git diff --staged --quiet; then
            git commit -m "Update AIS data - $(date -u +"%Y-%m-%d %H:%M UTC")"
            git push
          fi
